credentials       = "wazuh.json"
name              = "wazuh"
gcp_project       = "wazuh-gcp-376322"
region            = "us-central1"
zone              = "us-central1-a"
subnet_cidr_range = "10.0.0.0/16"
